env:
  node: true
  es2021: true
  mocha: true
  jest: true
extends:
  [
    "airbnb-base",
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
  ]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins: ["filenames", "classes", "@typescript-eslint"]
rules:
  {
    "filenames/match-exported": [2, "camel"],
    "classes/name": [2, "class", "method"],
    "import/extensions":
      [
        "error",
        "ignorePackages",
        { "js": "never", "jsx": "never", "ts": "never", "tsx": "never" },
      ],
  }
settings:
  import/resolver:
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
      moduleDirectory: ["src", "node_modules"]
